### ISSUE TITLE
Key.py

### ISSUE THREAD

**Issue by tmamedbekov** [Otterwerks/Tweet-Finder#1]
What is the Key.py format should look like?

**Comment by Otterwerks** [comment]
Hi, so the reason that Key.py is a separate file is because it uses authentication credentials generated from my twitter developer account and I wanted to hide it. The way authentication works for the twitter search API is that it requires the request header to have an "Authorization" key with a value that looks like "bearer \<alphanumeric string\>". So Key.py just has a single line of code and looks like this:`key = "bearer <alphanumeric string>"`. This page helps describe how to generate a bearer token https://developer.twitter.com/en/docs/basics/authentication/api-reference/token - you only need to make the oath2/token POST request once, then you can plug your token in and use it to authenticate for API requests. Hope this helps!

**Comment by tmamedbekov** [comment]
so i can do it with POSTMAN, and then plug it in, and I should it have it working locally without any issues?

**Comment by Otterwerks** [comment]
Exactly, you'll need to get your API keys by applying for a developer account and registering an App. You can then use basic auth in Postman with your API key as username and API secret key as password, and don't forget to add the parameter key "grant_type" with a value of "client_credentials".

**Comment by tmamedbekov** [comment]
Got the token generated, created ket.py, and then added "key = "bearer asdasdasfasdf" and I am keep getting an error > https://awesome-hoover-9de496.netlify.com/

**Comment by Otterwerks** [comment]
I tried to make a request using Postman for both Flask API endpoints and I'm getting 404 page not found for both. You probably have the key set up properly but something else is going on that is preventing access to Flask. How are you hosting everything? On Heroku I'm using gunicorn to run server.py and host everything.

**Comment by tmamedbekov** [comment]
Just ran a command ``npm run build``, and deployed to netlify. Should I be making any changes is I do not host on Heroku?

**Comment by Otterwerks** [comment]
Ah that's the problem, so only the front end is running on netlify. You need to have netlify run python for server.py to host everything and for the functionality to work correctly. I'm unfamiliar with netlify but it looks like you drag and drop files to deploy them? I'm reading https://www.netlify.com/docs/#python and it looks like it should work if you take the files from this repo and upload them, there is already a "build" folder so no need to run npm run build.

**Comment by Otterwerks** [comment]
I'll add a description of what key.py should look like in the README, along with better instructions for building and deploying.
